export const UETDS_COUNTRY_OPTIONS = [
  { code: 'TR', name: 'Türkiye' },
  { code: 'DE', name: 'Almanya' },
  { code: 'AT', name: 'Avusturya' },
  { code: 'AZ', name: 'Azerbaycan' },
  { code: 'AE', name: 'Birleşik Arap Emirlikleri' },
  { code: 'GB', name: 'Birleşik Krallık' },
  { code: 'BG', name: 'Bulgaristan' },
  { code: 'DZ', name: 'Cezayir' },
  { code: 'MA', name: 'Fas' },
  { code: 'FR', name: 'Fransa' },
  { code: 'GE', name: 'Gürcistan' },
  { code: 'NL', name: 'Hollanda' },
  { code: 'IQ', name: 'Irak' },
  { code: 'IR', name: 'İran' },
  { code: 'ES', name: 'İspanya' },
  { code: 'CH', name: 'İsviçre' },
  { code: 'SE', name: 'İsveç' },
  { code: 'IT', name: 'İtalya' },
  { code: 'JO', name: 'Ürdün' },
  { code: 'KZ', name: 'Kazakistan' },
  { code: 'KG', name: 'Kırgızistan' },
  { code: 'KW', name: 'Kuveyt' },
  { code: 'LB', name: 'Lübnan' },
  { code: 'EG', name: 'Mısır' },
  { code: 'UZ', name: 'Özbekistan' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'RO', name: 'Romanya' },
  { code: 'RU', name: 'Rusya' },
  { code: 'SA', name: 'Suudi Arabistan' },
  { code: 'SY', name: 'Suriye' },
  { code: 'TJ', name: 'Tacikistan' },
  { code: 'TN', name: 'Tunus' },
  { code: 'TM', name: 'Türkmenistan' },
  { code: 'UA', name: 'Ukrayna' },
  { code: 'OM', name: 'Umman' },
  { code: 'GR', name: 'Yunanistan' },
  { code: 'QA', name: 'Katar' },
  { code: 'US', name: 'Amerika Birleşik Devletleri' },
  { code: 'CA', name: 'Kanada' },
  { code: 'AU', name: 'Avustralya' },
  { code: 'BE', name: 'Belçika' },
  { code: 'CN', name: 'Çin' },
  { code: 'IN', name: 'Hindistan' },
] as const;
